apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hrf5vhhqh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hrf5vhhqh-go 
  name: hrf5vhhqh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hrf5vhhqh-go 
